    <fieldset class="fieldset create account">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Profile Picture') ?></span></legend><br>

        <div class="field promotion_code">
            <label for="customer_avatar" class="label"><span><?php /* @escapeNotVerified */ echo __('Avatar') ?></span></label>
            <div class="control">
                <input type="file" name="customer_avatar" id="customer_avatar" />
            </div>
        </div>
        
    </fieldset>
